### ISSUE TITLE
do_get should receive timeout as parameter

### ISSUE THREAD

**Issue by flavioribeiro** [igorsobreira/fms-admin-api#19]
Timeout connections between the fms-admin-client and the server should exists sometimes. To prevent or treat it, it should have a timeout parameter in do_get calls.

Ref: http://userprimary.net/posts/2008/04/13/setting-a-longer-timeout-for-nethttp-requests-in-ruby/

**Comment by hltbra** [comment]
@igorsobreira can you please send a new gem to rubygems?
